alias: null
batch_size: 32
channel_independence: 0
d_ff: 32
d_model: 32
decoder_input_size_multiplier: 0.5
decomp_method: moving_avg
down_sampling_layers: 1
down_sampling_method: avg
down_sampling_window: 2
drop_last_loader: false
dropout: 0.1
e_layers: 4
early_stop_patience_steps: 3
futr_exog_list: null
h: 18
hist_exog_list: null
input_size: 36
learning_rate: 0.001
loss: !!python/object:neuralforecast.losses.pytorch.MAE
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_always_called: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  horizon_weight: null
  is_distribution_output: false
  output_names:
  - ''
  outputsize_multiplier: 1
  training: true
lr_scheduler: null
lr_scheduler_kwargs: null
max_steps: 1000
moving_avg: 25
n_series: 1
num_lr_decays: -1
num_workers_loader: 0
optimizer: null
optimizer_kwargs: null
random_seed: 1
scaler_type: identity
stat_exog_list: null
step_size: 1
top_k: 5
use_norm: true
val_check_steps: 100
valid_loss: null
